#!/bin/sh

bearer=`cat bearer` || exit 1

curl --request POST \
  --url 'https://integrate.elluciancloud.com/api/persons' \
  --header 'Accept: application/vnd.hedtech.integration.v8+json' \
  --header 'Authorization: Bearer '"${bearer}" \
  --header 'Content-Type: application/vnd.hedtech.integration.v8+json' \
  --data ' {
  "credentials": [
    {
      "type": "bannerSourcedId",
      "value": ""
    },
    {
      "type": "bannerUdcId",
      "value": ""
    },
    {
      "type": "bannerId",
      "value": "H00030001"
    }
  ],
  "emails": [
    {
      "address": "pweasley@example.com",
      "type": {
        "detail": {
          "id": "00000000-0000-0000-0000-000000000000"
        },
        "emailType": "personal"
      }
    }
  ],
  "id": "00000000-0000-0000-0000-000000000000",
  "names": [
    {
      "firstName": "Percy",
      "fullName": "Percy Weasley",
      "lastName": "Weasley",
      "preference": "preferred",
      "type": {
        "category": "personal"
      }
    }
  ],
  "phones": [
    {
      "number": "5555551234",
      "type": {
        "detail": {
          "id": "00000000-0000-0000-0000-000000000000"
        },
        "phoneType": "home"
      }
    }
  ],
  "privacyStatus": {
    "privacyCategory": "unrestricted"
  }
}'
exit $?
