#!/bin/sh

bearer=`cat bearer` || exit 1
name=Potter
curl --request GET \
  --url 'https://integrate.elluciancloud.com/api/persons?criteria=%7b%22lastName%22:%22'"${name}"'%22%7d' \
  --header 'Accept: application/vnd.hedtech.integration.v8+json' \
  --header 'Authorization: Bearer '"${bearer}" \
  --verbose \
  --output specificPerson${name}.json
exit $?

